<div class="page-header" xmlns="http://www.w3.org/1999/html">
        <h1 class="page-title" id="history">About H+0 Engineering</h1>
    </div>
    <div class="row">
        <div class="col-md-4 right-column">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-tiltle">Page Content</h4>
                </div>
                <div class="panel-footer">
                    <ul style="list-style:none;">
                        <li>
                            <a href="#history">Company History</a>
                        </li>
                        <li>
                            <a href="#members">Members</a>
                            <ul style="list-style:none;">
                                <li>
                                    <a href="#member_a">Member A</a>
                                </li>
                                <li>
                                    <a href="#member_b">Member B</a>
                                </li>
                                <li>
                                    <a href="#member_c">Member C</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div id="history" class="col-md-8 left-column">
            <p>
                <?php echo $this->mission; ?>
            </p>
            <h2 id="founders">Founders</h2>
            <?php
                foreach( $this->founders AS $founder ) {
                    ?>
                        <div style="row">
                            <div class="col-md-5">
                                <img src="<?php echo $founder['image']; ?>" style="width:100%">
                            </div>
                            <div class="col-md-7" style="margin-top:-45px;padding:20px;">
                                    <h3 id="founder_a"><?php echo $founder['name']; ?></h3>
                                <p>
                                    phone: <?php echo $founder[ 'phone' ]; ?><br/>
                                    email: <?php echo $founder[ 'email']; ?>
                                </p>
                                <p><?php echo $founder['history']; ?></p>
                            </div>
                        </div>
                    <p style="clear:both;">&nbsp;</p>
            <?php
                }
            ?>
            <h2 class="members">Members</h2>
            <?php
                foreach( $this->members AS $member ) {
                    ?>
                        <div class="row">
                            <div class="col-md-5">
                                <img src="<?php echo $member[ 'image' ]; ?>" style="width:100%;">
                            </div>
                            <div class="col-md-7" style="margin-top:-45px;padding:20px;">
                                <h3><?php echo $member[ 'name' ]; ?></h3>
                                <p>
                                    phone: <?php echo $member[ 'phone' ]; ?><br/>
                                    email: <?php echo $member[ 'email']; ?>
                                </p>
                                <p><?php echo $member[ 'history' ]; ?></p>
                            </div>
                        </div>
                    <p style="clear:both;">&nbsp;</p>
            <?php
                }
            ?>
        </div>
    </div>
