    <div class="page-header">
        <h1 class="page-title" id="history">About H+0 Engineering</h1>
    </div>
    <div class="row">
        <div class="col-md-4 right-column">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-tiltle">Page Content</h4>
                </div>
                <div class="panel-footer">
                    <ul style="list-style:none;">
                        <li>
                            <a href="#history">Company History</a>
                        </li>
                        <li>
                            <a href="#members">Members</a>
                            <ul style="list-style:none;">
                                <li>
                                    <a href="#member_a">Member A</a>
                                </li>
                                <li>
                                    <a href="#member_b">Member B</a>
                                </li>
                                <li>
                                    <a href="#member_c">Member C</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div id="history" class="col-md-8 pull-right left-column">
            <p>
                <?php echo $this->mission; ?>
            </p>
            <h2 id="founders">Founders</h2>
            <?php
                foreach( $this->founders AS $founder ) {
                    ?>
                        <p>
                            <h3 id="founder_a"><?php echo $founder['name']; ?></h3>
                            <img src="<?php echo $founder['image']; ?>" style="float:left; width=300px;">
                            <?php echo $founder['history']; ?>
                        </p>
            <?php
                }
            ?>
            <h2 class="members">Members</h2>
            <?php
                foreach( $this->members AS $member ) {
                    ?>
                        <p>
                            <h3><?php echo $member[ 'name' ]; ?></h3>
                            <img src="<?php echo $member[ 'image' ]; ?>" style="float:left; width=250px;">
                            <?php echo $member[ 'history' ]; ?>
                        </p>
            <?php
                }
            ?>
        </div>
    </div>
