<div class="page-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12" style="padding-left:0px;">
                <h1 class="page-title" id="history">About H+0 Engineering</h1>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4 pull-right" style="border:1px solid #efefef;min-height:630px;">
        <div style="padding:10px;">
            <div class="panel panel-default">
                <div class="panel-body">
                    Page Content
                </div>
                <div class="panel-footer">
                    <ul style="list-style:none;">
                        <li>
                            <a href="#history">Company History</a>
                        </li>
                        <li>
                            <a href="#members">Members</a>
                            <ul style="list-style:none;">
                                <li>
                                    <a href="#member_a">Member A</a>
                                </li>
                                <li>
                                    <a href="#member_b">Member B</a>
                                </li>
                                <li>
                                    <a href="#member_c">Member C</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8 pull-right" style="border:1px solid #efefef;min-height:630px;">
        <div style="padding:10px;">
            <p>
                Information about the company will go here. It should describe how the company started.
                It should also mentioned about what services the company provides.
            </p>
            <h2 id="founders">Founders</h2>
            <p>
                <h3 id="founder_a">Founder A</h3>
                <img src="" style="float:left;"> Information about the member will go here. It should give a brief history about the
                member. Where s/he graduated from and his/her origin. It should also mentioned where s/he worked before  and the most
                import project s/he has worked on.
            </p>
            <p>
                <h3 id="founder_b">Founder B</h3>
                <img src="" style="float:left;"> Information about the member will go here. It should give a brief history about the
                member. Where s/he graduated from and his/her origin. It should also mentioned where s/he worked before  and the most
                import project s/he has worked on.
            </p>
            <p>
            <h2 class="members">Members</h2>
            <p>
                <h3>Member A</h3>
                    <img src="" style="float:left;"> Information about the member will go here. It should give a brief history about the
                    member. Where s/he graduated from and his/her origin. It should also mentioned where s/he worked before  and the most
                    import project s/he has worked on.
            </p>
            <h3 id="member_b">Member B</h3>
            <img src="" style="float:left;"> Information about the member will go here. It should give a brief history about the
            member. Where s/he graduated from and his/her origin. It should also mentioned where s/he worked before  and the most
            import project s/he has worked on.
            </p>
        </div>
    </div>
    <p>&nbsp;</p>
</div>
