<div class="page-header">
    <h2 class="page-title">Contact Information</h2>
</div>
<div id="contactPage">
    <div class="row">
        <div class="col-md-6">
            <div class="" style="padding:5px;">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3022.5593455498565!2d-73.95180338477029!3d40.74972077932779!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c2592791d2ed21%3A0x94e2209fc6add0c2!2s44-02+11th+St+%23406%2C+Long+Island+City%2C+NY+11101!5e0!3m2!1sen!2sus!4v1492483513547" width="100%" height="250" frameborder="0" style="border:2px solid white;margin-top:-5px;" allowfullscreen></iframe>
                <p>
                    For driving directions to this address click <a href="https://www.google.com/maps/dir//44-02+11th+St+%23406,+Long+Island+City,+NY+11101/@40.7497805,-73.9846342,13z/data=!3m1!4b1!4m9!4m8!1m0!1m5!1m1!1s0x89c2592791d2ed21:0x94e2209fc6add0c2!2m2!1d-73.9496147!2d40.7497208!3e0?hl=en-US" target="_blank">here</a>
                </p>
                <p>
                    Train Directions:</br>
                    Take the E or M train to Court Square - 23rd Street Station. Click <a href="https://www.google.com/maps/dir/Court+Square-23+Street/44-02+11th+St+%23406,+Long+Island+City,+NY+11101/@40.7488424,-73.9505568,17z/am=t/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x89c259285cf494d1:0x4e1109582c555306!2m2!1d-73.9472068!2d40.747956!1m5!1m1!1s0x89c2592791d2ed21:0x94e2209fc6add0c2!2m2!1d-73.9496147!2d40.7497208!5i1?hl=en-US" target="_blank">here</a> for walking directions from
                    this train station to our office.
                </p>
                <p>
                    <span class="glyphicon glyphicon-map-marker"></span>44-02 11th Street, Suite 406. Long Island City, NY 11101<br/>
                <span class="glyphicon glyphicon-phone-alt"></span> <a href="tel:3476390669">(347) 639-0669</a><br/>
<!--                    <i class="fa fa-fax"></i> 718.345.4731<br/>
-->                    <span class="glyphicon glyphicon-envelope"></span> info@handoeng.com
                </p>
            </div>
        </div>
        <div class="col-md-6">
            <form method=post id="contactForm" action="/contact/send">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>Send Us An Email</h3>
                </div>
                <div class="panel-body">
                    <p>
                        The more information you provide, the easier it will be for us to respond to you quicker.
                    </p>
                    <p>
                        Note that all the fields are required.
                    </p>
                            <div class="form-group">
                                <div class="col-md-2 label">
                                    <label class="control-label">Name</label>
                                </div>
                                <div class="col-md-10">
                                    <input type="text" class="form-control medium-input" name="name" value="">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-2 label">
                                    <label class="control-label">Email</label>
                                </div>
                                <div class="col-md-10">
                                    <input type="email" class="form-control" name="email" value="">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-2 label">
                                    <label class="control-label">Phone</label>
                                </div>
                                <div class="col-md-10">
                                    <input type="phone" class="form-control" name="phone" value="">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-2 label">
                                    <label class="control-label">Subject</label>
                                </div>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="subject" value="">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-2 label">
                                    <label class="control-label">Message</label>
                                </div>
                                <div class="col-md-10">
                                    <textarea name="message" class="form-control" rows="10"></textarea>
                                </div>
                            </div>
                </div>
                <div class="panel-footer">
                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-6"></div>
                            <div class="col-md-6">
                                <input type="reset"  name="cancel" class="btn btn-warning btn-lg" value="Reset">
                                <input type="submit" name="save"  class="btn btn-lg btn-primary" value="Send Message&raquo;">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
var contact = {
	init:function(){
		this.mPage = $( '#contactPage' );
		this.mForm = $( '#contactForm' );
		this.events();
		
		FormValidator.init( {
			'name':{
				required:true,
				type:'input'
			},
			'email':{
				required:true,
				type:'email'
			},
			'phone':{
				required:true,
				type:'phone'
			},
			'subject':{
				required:true,
				type:'input'
			},
			'message':{
				required:true,
				type:'textarea'
			},
			'save':{
				required:false,
				type:'button',
			},
			'cancel':{
				required:false,
				type:'button',
			}
		}, 'contactForm' );
	},
	
	events:function(){
		this.mForm.on( 'submit', {parent:this}, this.ui.onSubmit);
	},
	
	ui:{
		onSubmit:function( e ){		
			if( !FormValidator.validate( ) ){
				alert( 'we are unable to send your request. Please fill out all the field(s) in red');
				e.preventDefault();
				return;
			}
			
			console.log( 'form is good to submit' );
		}
	}
	
	
};

var FormValidator={
	init:function( required, formID ){
		this.mFormID = formID ;
		this.mErrors = false;
		
		if( this.mFormID.length == 0 ){
			console.log( 'Could not instantiate form validator due to formID provided' );
			return;
		}
		this.mRequired = required;
		this.mForm = $( '#'+this.mFormID );
		this.events();
	},
	
	events:function(){
		this.mForm.on( 'focusout', 'input[type=text], input[type=email], input[type=phone], input[type=date], input[type=hidden], textarea, select', {parent:this}, this.ui.onFocusOut);
	},
	
	ui:{
		onFocusOut:function( e ){
			console.log( 'Field '+this.name );
			if( e.data.parent.mRequired[ this.name ].required && !e.data.parent.fieldValidate( this ) ){
				console.log( 'There are errors in the following element: '+this.name );
				e.data.parent.mErrors = true;
			}
		}
	},
	
	validate:function(){
		var elements = document.getElementById( this.mFormID ).elements;
		this.mErrors = false;
		var that = this;
		
		$.each( elements, function( index, element ){
			if( that.mRequired[ element.name ].required){
				if( !that.fieldValidate( element ) ){
					console.log( 'there are errors in the following element '+element.name );
					this.mErrors = true;
				}
			}	
		});		
		
		return !this.mErrors;
	},
	
	fieldValidate:function( element ){		
		
		switch( element.type ){
			case 'text':
			case 'textarea':
			case 'email':
			case 'phone':
			case 'date':
				if( element.value.length == 0 ){
					$( element ).closest( '.form-group' ).addClass( 'has-error' );
					return false;
				}
				
				$( element ).closest( '.form-group' ).removeClass( 'has-error');
				return true;
			case 'radio':
			
				break;
				
			case 'select':
				
				break;
				
			default:
				console.log( element.type +' is not validated yet. Added to the list so it can be validated' );
		}
		
	}
}

$( function(){
	contact.init();
});
</script>