<div class="page-header">
    <div class="container">
        <h1 title="page-title">
            Contact Information
        </h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-success">
                <div class="panel-heading" style="background:#fcb13e;color:white;">
                    <h4>Your message was received successfully!</h4>
                </div>
                <div class="panel-body">
                    <p>
                        Thank you for contacting us. We will get back at you as soon as possible. If you concern needs immediate attention,
                        I suggest that you give us a call to the following number. 718-945-3291
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <p>
                <a style="padding:7px;" target="_blank" title="follow on facebook" href="https://www.facebook.com/handoengineer?ref=hl">
                    <i class="fa fa-facebook-square fa-3x"></i>
                </a>
                <a style="padding:7px;" target="_blank" title="follow on instagram" href="https://www.instagram.com/handoengineer?ref=hl">
                    <i class="fa fa-instagram fa-3x"></i>
                </a>
                <a style="padding:7px;" target="_blank" title="follow on twitter" href="https://www.twitter.com/handoengineer?ref=hl">
                    <i class="fa fa-twitter fa-3x"></i>
                </a>
            </p>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3022.228307996101!2d-73.88816299999999!3d40.75700299999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25fa0b00f3f93%3A0xe3cddaa073afdb2a!2s32-11+79th+St%2C+East+Elmhurst%2C+NY+11370!5e0!3m2!1sen!2sus!4v1442456570564" width="100%" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>
            <h3>H & O Engineering</h3>
            <p>
                <span class="glyphicon glyphicon-map-marker"></span>32-11 79th Street,
                E. Elmhurst, NY 11370
            </p>
            <p>
                For driving directions to this address click <a href="https://www.google.com/maps/dir//32-11+79th+St,+East+Elmhurst,+NY+11370/@40.757011,-73.8927764,16z/data=!3m1!4b1!4m8!4m7!1m0!1m5!1m1!1s0x89c25fa0b00f3f93:0xe3cddaa073afdb2a!2m2!1d-73.888163!2d40.757003" target="_blank">here</a>
            </p>
            <p>
                <span class="glyphicon glyphicon-phone-alt"></span> (347) 859-9891<br/>
                fax 718.345.4731<br/>
                <span class="glyphicon glyphicon-envelope"></span> info@handoeng.com
            </p>
            <p>
                <b>Train Directions:</b></br>
                To get to our office by train take the 7 train to 74 St - Broadway Station or the E, F, M, R to Roosevelt Ave - Jackson Heights Station. Click <a href="https://www.google.com/maps/dir/31-11+79th+St,+East+Elmhurst,+NY+11370/74+St+-+Broadway,+Queens,+NY+11372/@40.7527341,-73.8993578,15z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x89c25fa09c5e7985:0x9e287b7453eabe08!2m2!1d-73.8887287!2d40.758512!1m5!1m1!1s0x89c25f00d30856f7:0x8a8c21245253fdfa!2m2!1d-73.891495!2d40.7469245!3e2">here</a> for walking directions from
                this train station to our office.
            </p>
        </div>
    </div>
</div>