<div class="page-header">
    <h2 class="page-title">Planning & Demolition Services</h2>
</div>

<div class="row" >
    <div class="col-md-12">
        <ul class="services">
            <li style="border-top:0px;">Structural design</li>

            <li>Pre-Construction Survey</li>

            <li>Site Safety Plans</li>

            <li>Special Inspections</li>

            <li>Monitoring</li>

            <li>Means and Methods for Demolition</li>

        </ul>
    </div>
</div>

