<!--
<div class="row">
        <div class="col-md-12">

            <div class="page-header" style="margin-top:80px;background-image:linear-gradient(to bottom,#f5f5f5 0,#e8e8e8 100%);">
    <h2 class="page-title" style="background-image:linear-gradient(to bottom,rgba(252, 177, 62, 0.74) 0,rgba(240, 173, 78, 0.68) 100%);color:white;padding:10px;">About us</h2>
    <p style="padding:10px;font-size:1.12em;color:rgba(240, 173, 78, 0.83);">
        H & O Engineering is an engineering firm offering a wide variety of structural related design and construction services,
        with the vast majority of projects located in the New York City area. We are dedicated to serving our clients in the most
        efficient and responsive manner--we are well aware of the tight schedule that projects face.  We can offer you experience,
        a wide range of engineering knowledge, and the all-important ability to navigate through city agencies like The Department of Buildings,
        NYC Transit Authority, LIRR, etc -- everything needed to help your project move as smoothly as possible from start to finish.
    </p>
</div>
            </div>
</div>
-->
<div class="row" >
    <div class="col-md-12">
        <ul class="services">
            <h1 style="background-image: linear-gradient(to bottom,rgba(252, 177, 62, 0.08) 0,rgba(255,255,255,0.15) 100%);padding:10px;color:rgba(68, 63, 63, 0.57);margin-bottom:-5px;margin-top:33px;margin-top:-1px;margin-left:-40px;">
                Our services:
            </h1>
            <li style="border-top:0px;"><span><img src="img/structuraldesign.jpg"></span>Structural design</li>

            <li><span><img src="img/survey.jpg"></span>Pre-Construction Survey</li>

            <li><span><img src="img/site_safety.jpg"></span>Site Safety Plans</li>

            <li><span><img src="img/inspection.jpg"></span>Special Inspections</li>

            <li><span><img src="img/monitoring1.jpg"></span>Monitoring</li>

            <li><span><img src="img/demolition1.jpg"></span>Means and Methods for Demolition</li>

        </ul>
    </div>
</div>

