<div class="page-header">
    <h2 class="page-title">Planning & Demolition Services</h2>
</div>

<div class="row">
    <div class="col-md-8">
        <p>
            For building inspections, rehabilitations, or demolitions. Call today for your free consultation: <a href="tel:3476390669">(347) 639-0669</a>
        </p>
        <strong>We provide the following services for new or existing buildings or structures.</strong><br/>
        <ul>
            <li>Complete building rehabilitation, including site and structural condition evaluation</li>
            <li>Full assessment of potential rehabilitation methods, rehabilitation design.</li>
            <li>Final approval and the procurement of all proper permits.</li>
        </ul>
        <strong>Our services include the following structural engineering services:</strong>
        <ul>
            <li>Structural design for steel, concrete, and wood</li>
            <li>Structural design of excavation</li>
            <li>Controlled inspection services</li>
            <li>Structural reports</li>
            <li>Repair and rehabilitation</li>
            <li>Demolition plans</li>
        </ul>
            <strong>Complete consulting services for buildings of all types including but not limited to:</strong><br/>
                <ul>
                    <li>Residential buildings</li>
                    <li>Houses</li>
                    <li>Townhouses</li>
                    <li>High rises</li>
                    <li>Hospitals</li>
                    <li>Commercial buildings</li>
                    <li>Hotels</li>
                    <li>Stores</li>
                    <li>Office buildings</li>
                </ul>
        <p>
            Call today at <a href="tel:3476390669">(347) 639-0669</a> for a free consultation.
        </p>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading" style="background:#fcb13e;padding:10px;color:white;font-weight:bolder;font-size:18px;">
                <p>
                    Free Consultation
                    call  <a href="tel:3476390669">(347) 639-0669</a>
                </p>
            </div>
            <div class="panel-body">
                <p>
                    <a href="#planning">Planning services</a>
                </p>
                <p>
                    <a href="#demolition">Demolition services</a>
                </p>

            </div>
        </div>
    </div>
</div>

