<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('H and O Engineering'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');

        ?>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
			<script type="text/javascript" src="/js/ticket.js"></script>
        <style>
            html, body {
                width: 100%;
                height: 100%;
                margin:0;
            }
        </style>
    </head>
    <body>
        <div class="container" style="height:100%;">
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="background:#F3F1F2;border:0px;">
            <div class="container"  style="border:0;">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/"><img src="/img/websiteLogogray.jpg"></a>
                </div>
                <div class="collapse navbar-collapse move-right">
                    <ul class="nav navbar-nav">
                        <li><a href="/">Home</a></li>
<!--                        <li><a href="/about-us">About Us</a></li>
-->                        <li><a href="/services">Services</a></li>
<!--                        <li><a href="/projects">Projects</a></li>
-->                        <li><a href="/contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="main">
            <?php echo $this->content; ?>
        </div>
        <footer style="position:relative;background-color:#fcb13e;color:#f5f5f5;height:50%;padding-top:10px;padding-bottom:0px;font-size:13px;">
                <div style="padding:10px;display:block;position:relative;top:100%;background-color:#fcb13e;color:#f5f5f5">
                    <span style="">&copy; 2015 - <?php echo date('Y') ?> H and O Engineering, DPC. <?php echo $this->translate('All rights reserved.') ?></span>
                </div>
        </footer>
        <?php echo $this->inlineScript() ?>
        </div>
    </body>
</html>
