<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('H and O Engineering'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');

        ?>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
			<script type="text/javascript" src="/js/ticket.js"></script>
        <style>
            html, body {
                width: 100%;
                height: 100%;
                margin:0;
            }
        </style>
        <script>
            window['_fs_debug'] = false;
            window['_fs_host'] = 'fullstory.com';
            window['_fs_org'] = '6T6R3';
            window['_fs_namespace'] = 'FS';
            (function(m,n,e,t,l,o,g,y){
                if (e in m) {if(m.console && m.console.log) { m.console.log('FullStory namespace conflict. Please set window["_fs_namespace"].');} return;}
                g=m[e]=function(a,b){g.q?g.q.push([a,b]):g._api(a,b);};g.q=[];
                o=n.createElement(t);o.async=1;o.src='https://'+_fs_host+'/s/fs.js';
                y=n.getElementsByTagName(t)[0];y.parentNode.insertBefore(o,y);
                g.identify=function(i,v){g(l,{uid:i});if(v)g(l,v)};g.setUserVars=function(v){g(l,v)};
                g.identifyAccount=function(i,v){o='account';v=v||{};v.acctId=i;g(o,v)};
                g.clearUserCookie=function(c,d,i){if(!c || document.cookie.match('fs_uid=[`;`]*`[`;`]*`[`;`]*`')){
                    d=n.domain;while(1){n.cookie='fs_uid=;domain='+d+
                        ';path=/;expires='+new Date(0).toUTCString();i=d.indexOf('.');if(i<0)break;d=d.slice(i+1)}}};
            })(window,document,window['_fs_namespace'],'script','user');
        </script>
    </head>
    <body>
        <div class="container" style="height:100%;">
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="background:#f7fbfa;border:0px;">
            <div class="container"  style="border:0;">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/"><img src="/img/logoGrayBackground.jpg"></a>
                </div>
                <div class="collapse navbar-collapse move-right">
                    <ul class="nav navbar-nav">
                        <li><a href="/">Home</a></li>
<!--                        <li><a href="/about-us">About Us</a></li>
-->                        <li><a href="/services">Services</a></li>
<!--                        <li><a href="/projects">Projects</a></li>
-->                        <li><a href="/contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="main">
            <?php echo $this->content; ?>
        </div>
        <footer style="position:relative;background-color:#fcb13e;color:#f5f5f5;height:100px;padding-top:10px;padding-bottom:0px;font-size:13px;">
                <div style="padding:10px;display:block;position:relative;top:100%;background-color:#fcb13e;color:#f5f5f5">
                    <span style="">&copy; 2015 - <?php echo date('Y') ?> H and O Engineering, DPC. <?php echo $this->translate('All rights reserved.') ?></span>
                </div>
        </footer>
        <?php echo $this->inlineScript() ?>
        </div>
    </body>
</html>
