<h3 class="page-title">
    Create Ticket
</h3>
<ul class="page-breadcrumb breadcrumb">
    <li class="btn-group">
    </li>
    <li>
        <i class="fa fa-home"></i>
        <a href="/">Home</a>
        <i class="fa fa-angle-right"></i>
    </li>
    <li>
        <a href="/helpdesk/tickets">Tickets</a>
        <i class="fa fa-angle-right"></i>
    </li>
    <li>
        <a href="/helpdesk/tickets/create">Create Ticket</a>
    </li>
</ul>
<form method="post" id="ticketForm" onSubmit="return validateTicketForm();">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group"  id="title_error">
                <label>Ticket Title</label><br/>
                <input type="text" class="form-control input-medium" name="title" placeholder="ticket title">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group" id="users_error">
                <label>Assign User</label>
                <select name="users" id="usersDropdown" class="form-control input-medium">
                    <option value="">Select a user</option>
                </select>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group" id="description_error">
                <label>Ticket Description</label><br/>
                <textarea name="description" class="form-control input-medium"></textarea>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group" id="files_error">
                <label>File</label><br/>
                <input type="file" name="files" class="form-control input-medium">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <input type="submit" class="btn btn-default btn-primary" value="Submit&raquo;">
            <input type="reset" class="btn btn-default btn-warning" value="Reset">
        </div>

    </div>
</form>
