<h1>Projects</h1>
<hr>

<div class="row">
    <div class="col-md-3 odd">
      <h2>Project 1</h2>
        <img src="">
        <p>
            Brief description of the project should go here. Try to include top 5 main points of the work and what it was done by the company.
        </p>
        <p class="pull-right">
            <a href="projects/1" class="btn btn-default">More Information&raquo;</a>
        </p>
    </div>
    <div class="col-md-3 even">
        <h2>Project 2</h2>
        <img src="">
        <p>
            Brief description of the project should go here. Try to include top 5 main points of the work and what it was done by the company.
        </p>
        <p class="pull-right">
            <a href="projects/1" class="btn btn-default">More Information&raquo;</a>
        </p>
    </div>
    <div class="col-md-3 odd">
        <h2>Project 3</h2>
        <img src="">
        <p>
            Brief description of the project should go here. Try to include top 5 main points of the work and what it was done by the company.
        </p>
        <p class="pull-right">
            <a href="projects/1" class="btn btn-default">More Information&raquo;</a>
        </p>
    </div>
    <div class="col-md-3 even">
        <h2>Project 4</h2>
        <img src="">
        <p>
            Brief description of the project should go here. Try to include top 5 main points of the work and what it was done by the company.
        </p>
        <p class="pull-right">
            <a href="projects/1" class="btn btn-default">More Information&raquo;</a>
        </p>
    </div>
</div>
<div class="row">
    <div class="col-md-3 odd">
        <h2>Project 5</h2>
        <img src="">
        <p>
            Brief description of the project should go here. Try to include top 5 main points of the work and what it was done by the company.
        </p>
        <p class="pull-right">
            <a href="projects/1" class="btn btn-default">More Information&raquo;</a>
        </p>
    </div>
    <div class="col-md-3 even">
        <h2>Project 6</h2>
        <img src="">
        <p>
            Brief description of the project should go here. Try to include top 5 main points of the work and what it was done by the company.
        </p>
        <p class="pull-right">
            <a href="projects/1" class="btn btn-default">More Information&raquo;</a>
        </p>
    </div>
    <div class="col-md-3 odd">
        <h2>Project 7</h2>
        <img src="">
        <p>
            Brief description of the project should go here. Try to include top 5 main points of the work and what it was done by the company.
        </p>
        <p class="pull-right">
            <a href="projects/1" class="btn btn-default">More Information&raquo;</a>
        </p>
    </div>
    <div class="col-md-3 even">
        <h2>Project 8</h2>
        <img src="">
        <p>
            Brief description of the project should go here. Try to include top 5 main points of the work and what it was done by the company.
        </p>
        <p class="pull-right">
            <a href="projects/1" class="btn btn-default">More Information&raquo;</a>
        </p>
    </div>
</div>