<div class="page-header">
     <h1 class="page-title">Projects</h1>
</div>
    <div class="row">
    <?php
        $classes = [
            0 => 'even',
            1 => 'odd'
        ];
        $size = count( $this->projects );

        for( $i = 0; $i < $size; $i++ ){
            if( $i > 0 && $i%4 == 0 ){
                echo '</div><div class="row">';
            }
            echo '<div class="col-md-3 '.$classes[ $i%2 ].'"><div>';
                echo '<h3>'.$this->projects[ $i ][ 'title'].'</h3>';
                echo '<img src="'.$this->projects[ $i ][ 'image' ].'" width="100%">';
                echo '<p>'.$this->projects[ $i ][ 'description' ].'</p>';
                echo '<p class="pull-right">';
                    echo '<a href="/contact" class="btn btn-default">More Information&raquo;</a>';
                echo '</p>';
            echo '</div></div>';
        }
    ?>
    </div>