<div class="page-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12" style="padding-left:0px;">
                <h1 class="page-title">Projects</h1>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-3 odd">
            <div>
                <h3>Project 1</h3>
                <img src="http://www.bustler.net/images/news2/2013_aia_institute_honor_awards_-_architecture-06.jpg" width="100%">
                <p>
                    Brief description of the project should go here. Try to include top 5 main points of the work and what it was done by the company.
                </p>
                <p class="pull-right">
                    <a href="projects/1" class="btn btn-default">More Information&raquo;</a>
                </p>
            </div>
        </div>
        <div class="col-md-3 even">
            <div>
                <h3>Project 2</h3>
                <img src="http://www.oneworld365.org/img/101/Architecture%20Internships%20Abroad.jpg" width="100%">
                <p>
                    Brief description of the project should go here. Try to include top 5 main points of the work and what it was done by the company.
                </p>
                <p class="pull-right">
                    <a href="projects/1" class="btn btn-default">More Information&raquo;</a>
                </p>
            </div>
        </div>
        <div class="col-md-3 odd">
            <div>
                <h3>Project 3</h3>
                <img src="http://bedroomkitchen.com/wp-content/uploads/2014/01/architecture-design-606.jpg" width="100%">
                <p>
                    Brief description of the project should go here. Try to include top 5 main points of the work and what it was done by the company.
                </p>
                <p class="pull-right">
                    <a href="projects/1" class="btn btn-default">More Information&raquo;</a>
                </p>
            </div>
        </div>
        <div class="col-md-3 even">
            <div>
                <h3>Project 4</h3>
                <img src="https://secure.static.tumblr.com/b05009699d8487b856765345d7d5a8d6/duj1jbc/iZxn33osm/tumblr_static_architectural_drawing_4.jpg" width="100%">
                <p>
                    Brief description of the project should go here. Try to include top 5 main points of the work and what it was done by the company.
                </p>
                <p class="pull-right">
                    <a href="projects/1" class="btn btn-default">More Information&raquo;</a>
                </p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 odd">
            <div>
                <h3>Project 5</h3>
                <img src="http://www.parentscountdowntocollegecoach.com/wp-content/uploads/2013/09/rolls-architecture-blueprint-work-tools-14438775.jpg" width="100%">
                <p>
                    Brief description of the project should go here. Try to include top 5 main points of the work and what it was done by the company.
                </p>
                <p class="pull-right">
                    <a href="projects/1" class="btn btn-default">More Information&raquo;</a>
                </p>
            </div>
        </div>
        <div class="col-md-3 even">
            <div>
                <h3>Project 6</h3>
                <img src="http://walldays.com/wp-content/uploads/2015/03/modern-architecture-sketches-hd-wallpapers-53131.jpg" width="100%">
                <p>
                    Brief description of the project should go here. Try to include top 5 main points of the work and what it was done by the company.
                </p>
                <p class="pull-right">
                    <a href="projects/1" class="btn btn-default">More Information&raquo;</a>
                </p>
            </div>
        </div>
        <div class="col-md-3 odd">
            <div>
                <h3>Project 7</h3>
                <img src="http://newshour-tc.pbs.org/newshour/wp-content/blogs.dir/1/files/slideshow/mos-floatinghouse_model_slideshow.jpg" width="100%">
                <p>
                    Brief description of the project should go here. Try to include top 5 main points of the work and what it was done by the company.
                </p>
                <p class="pull-right">
                    <a href="projects/1" class="btn btn-default">More Information&raquo;</a>
                </p>
            </div>
        </div>
        <div class="col-md-3 even">
            <div>
                <h3>Project 8</h3>
                <img src="http://image.guardian.co.uk/sys-images/Arts/Arts_/Pictures/2007/12/05/architecture460.jpg" width="100%">
                <p>
                    Brief description of the project should go here. Try to include top 5 main points of the work and what it was done by the company.
                </p>
                <p class="pull-right">
                    <a href="projects/1" class="btn btn-default">More Information&raquo;</a>
                </p>
            </div>
        </div>
    </div>
    <p>&nbsp;</p>
</div>