<div class="jumbotron" style="background-color:white;">
    <img src="img/largeLogoNoBackground.jpg" width="100%">
</div>
<h1>Projects</h1>
<div class="row">
    <div class="col-md-4">
        <h3>Project 1</h3>
        <img src="">
        <p>Small description here</p>
        <a href="">More Information&raquo;</a>
    </div>
    <div class="col-md-4">
        <h3>Project 1</h3>
        <img src="">
        <p>Small description here</p>
        <a href="">More Information&raquo;</a>
    </div>
    <div class="col-md-4">
        <h3>Project 1</h3>
        <img src="">
        <p>Small description here</p>
        <a href="">More Information&raquo;</a>
    </div>
</div>