<div class="container">
    <div class="row" style="padding:0px;">
        <div classs="col-md-12"  style="padding:0;">
            <div class="jumbotron">
                <span class="message">
                        WE'RE <span style="color:#fcb13e;">HEADLINE</span><br/>
                    <a href="" style="background-color:#707070;color:white;font-size:16px;padding:5px;"><span style="color:#fcb13e;">+</span>learn more</a>
                </span>
                <img src="img/structure1Image.jpg" width="100%">
            </div>
        </div>
    </div>
</div>
