    <div class="jumbotron"style="margin-top:-320px;">
        <p class="message" style="font-size: 0.70em;width: 382px;background-color: rgba(255, 255, 255, 0.08);left: 12px;padding: 15px;top: 396px;">
<!--                We offer a wide variety of <span style="color:#fcb13e;">structural related design</span> and <span  style="color:#fcb13e;">construction services</span>.
            We  offer experience, a wide range of engineering knowledge, and the ability to navigate
            through city agencies
            to help your project move as smoothly as possible from start to finish.<br/><br/>
-->
            We are an engineering firm offering a wide variety of <span style="color:#fcb13e;">structural related design</span> and <span style="color:#fcb13e;">construction services</span>,
            with the vast majority of projects located in the New York City area. We are dedicated to serving our clients in the most
            efficient and responsive manner--we are well aware of the tight schedule that projects face.  We can offer you experience,
            a wide range of engineering knowledge, and the all-important ability to navigate through city agencies like The Department of Buildings,
            NYC Transit Authority, LIRR, etc -- everything needed to help your project move as smoothly as possible from start to finish.<br/><br/>
            <a href="/services" style="background-color:#707070;color:white;font-size:16px;padding:5px;"><span style="color:#fcb13e;">+</span>learn more&gt;&gt;</a>
        </p>
        <img src="img/structure1Image.jpg" width="100%">
    </div>
    <div class="mobile-version">
        <img src="img/structure1Image.jpg" width="100%">
        <p style="font-size: 0.70em;padding:15px;">
            <!--                We offer a wide variety of <span style="color:#fcb13e;">structural related design</span> and <span  style="color:#fcb13e;">construction services</span>.
                        We  offer experience, a wide range of engineering knowledge, and the ability to navigate
                        through city agencies
                        to help your project move as smoothly as possible from start to finish.<br/><br/>
            -->
            We are an engineering firm offering a wide variety of <span style="color:#fcb13e;">structural related design</span> and <span style="color:#fcb13e;">construction services</span>,
            with the vast majority of projects located in the New York City area. We are dedicated to serving our clients in the most
            efficient and responsive manner--we are well aware of the tight schedule that projects face.  We can offer you experience,
            a wide range of engineering knowledge, and the all-important ability to navigate through city agencies like The Department of Buildings,
            NYC Transit Authority, LIRR, etc -- everything needed to help your project move as smoothly as possible from start to finish.<br/><br/>
            <a href="/services" style="background-color:#707070;color:white;font-size:16px;padding:5px;"><span style="color:#fcb13e;">+</span>learn more&gt;&gt;</a>
        </p>
    </div>
